"""Two-electron full-CI exact diagonalization for FEniCSx orbitals.

The mesh coordinates must be in nm and orbital energies in eV, matching
Schrodinger_Solver. The Coulomb Poisson problem is
    -div(eps_r grad W_qs) = 4*pi*conj(phi_q)*phi_s,
so W has units nm^-1 and e2_over_4pieps0 * integral(...) is in eV.
"""
import numpy as np
import ufl
from mpi4py import MPI
from petsc4py import PETSc
from dolfinx import fem
from dolfinx.mesh import exterior_facet_indices


class ExchangeInteractionED:
    E2_OVER_4PI_EPS0 = 1.4399645478425669  # eV*nm

    def __init__(self, domain, orbitals, orbital_energies, eps_r=11.7,
                 log_writer=None, verbose=False):
        if len(orbitals) != len(orbital_energies):
            raise ValueError("orbitals and orbital_energies must have equal length")
        if len(orbitals) < 2:
            raise ValueError("At least two one-electron orbitals are required")
        self.domain = domain
        self.orbitals = list(orbitals)
        self.energies = np.asarray(orbital_energies, dtype=float)
        self.M = len(orbitals)
        self.V = orbitals[0].function_space
        self.eps_r = fem.Constant(domain, PETSc.ScalarType(eps_r)) if np.isscalar(eps_r) else eps_r
        self.log_writer = log_writer
        self.verbose = verbose
        self.dx = ufl.Measure("dx", domain=domain)
        self._normalize_orbitals()

    def _msg(self, text):
        if self.domain.comm.rank == 0 and self.verbose:
            print(text)
        if self.log_writer is not None:
            self.log_writer.write(text)

    def _global_scalar(self, form):
        local = fem.assemble_scalar(fem.form(form))
        return self.domain.comm.allreduce(local, op=MPI.SUM)

    def _normalize_orbitals(self):
        for i, psi in enumerate(self.orbitals):
            n2 = self._global_scalar(ufl.conj(psi) * psi * self.dx)
            n2 = float(np.real(n2))
            if n2 <= 0.0:
                raise ValueError(f"Orbital {i} has non-positive norm {n2}")
            psi.x.array[:] /= np.sqrt(n2)
            psi.x.scatter_forward()

    def _zero_boundary_bc(self):
        tdim = self.domain.topology.dim
        self.domain.topology.create_connectivity(tdim - 1, tdim)
        facets = exterior_facet_indices(self.domain.topology)
        dofs = fem.locate_dofs_topological(self.V, tdim - 1, facets)
        zero = fem.Function(self.V)
        zero.x.array[:] = 0.0
        return fem.dirichletbc(zero, dofs)

    def _pair_potential(self, q, s):
        """Solve for W_qs generated by conj(phi_q)*phi_s."""
        u = ufl.TrialFunction(self.V)
        v = ufl.TestFunction(self.V)
        rho_qs = ufl.conj(self.orbitals[q]) * self.orbitals[s]
        a = ufl.inner(self.eps_r * ufl.grad(u), ufl.grad(v)) * self.dx
        L = PETSc.ScalarType(4.0 * np.pi) * ufl.inner(rho_qs, v) * self.dx
        problem = fem.petsc.LinearProblem(
            a, L, bcs=[self._zero_boundary_bc()],
            petsc_options_prefix=f"coulomb_{q}_{s}_",
            petsc_options={"ksp_type": "cg", "pc_type": "gamg", "ksp_rtol": 1e-10},
        )
        W = problem.solve()
        W.x.scatter_forward()
        return W

    def build_two_electron_hamiltonian(self):
        """Return H in ordered product basis |p(1) q(2)> and Coulomb tensor."""
        m = self.M
        coulomb = np.zeros((m, m, m, m), dtype=np.complex128)

        # V[p,q,r,s] = <p(1)q(2)|r12^-1|r(1)s(2)> * constant
        for q in range(m):
            for s in range(m):
                W_qs = self._pair_potential(q, s)
                for p in range(m):
                    for r in range(m):
                        value = self._global_scalar(
                            ufl.conj(self.orbitals[p]) * self.orbitals[r] * W_qs * self.dx
                        )
                        coulomb[p, q, r, s] = self.E2_OVER_4PI_EPS0 * value
                self._msg(f"[ED] Coulomb pair ({q + 1}/{m}, {s + 1}/{m}) completed")

        H = np.zeros((m * m, m * m), dtype=np.complex128)
        for p in range(m):
            for q in range(m):
                i = p * m + q
                H[i, i] += self.energies[p] + self.energies[q]
                for r in range(m):
                    for s in range(m):
                        H[i, r * m + s] += coulomb[p, q, r, s]

        # Remove integration/solver roundoff before diagonalization.
        H = 0.5 * (H + H.conj().T)
        return H, coulomb

    def solve(self, symmetry_tolerance=1e-6):
        """Diagonalize and return lowest singlet, triplet, and J = ET - ES."""
        H, coulomb = self.build_two_electron_hamiltonian()
        evals, evecs = np.linalg.eigh(H)
        m = self.M

        # Particle-swap operator P12; +1 spatial symmetry => spin singlet,
        # -1 spatial symmetry => spin triplet.
        swap = np.zeros_like(H)
        for p in range(m):
            for q in range(m):
                swap[q * m + p, p * m + q] = 1.0

        singlets, triplets = [], []
        for k, energy in enumerate(evals):
            c = evecs[:, k]
            parity = float(np.real(np.vdot(c, swap @ c)))
            item = {"energy": float(np.real(energy)), "coefficients": c,
                    "exchange_parity": parity}
            if parity > 1.0 - symmetry_tolerance:
                singlets.append(item)
            elif parity < -1.0 + symmetry_tolerance:
                triplets.append(item)

        if not singlets or not triplets:
            raise RuntimeError("Could not identify both exchange-symmetry sectors")

        result = {
            "singlet_energy": singlets[0]["energy"],
            "triplet_energy": triplets[0]["energy"],
            "exchange_J": triplets[0]["energy"] - singlets[0]["energy"],
            "singlet": singlets[0], "triplet": triplets[0],
            "all_energies": evals, "coulomb_tensor": coulomb,
        }
        self._msg(f"[ED] ES = {result['singlet_energy']:.12e} eV")
        self._msg(f"[ED] ET = {result['triplet_energy']:.12e} eV")
        self._msg(f"[ED] J  = {result['exchange_J']:.12e} eV")
        return result
